// 生成版本号并写入 public/version.txt（供线上 curl 验证）+ public/version.json（前端更新检测）+ lib/version.ts（页面显示）。
// 版本格式：YYYYMMDD-HHmm-<git short hash>，每次构建前运行。
// 用法：node scripts/make-version.mjs [--note "更新说明"]
// note 优先级：--note 参数 > 环境变量 NOTE > git 最近提交信息 > 空
import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

function run(cmd) {
  try {
    return execSync(cmd, { cwd: root, encoding: "utf8" }).trim();
  } catch {
    return "";
  }
}

function shortHash() {
  return run("git rev-parse --short HEAD") || "nogit";
}

// 更新说明：--note 参数 > NOTE 环境变量 > git 最近提交信息
const argv = process.argv.slice(2);
let note = "";
const noteIdx = argv.indexOf("--note");
if (noteIdx !== -1 && argv[noteIdx + 1]) note = argv[noteIdx + 1];
else if (process.env.NOTE) note = process.env.NOTE;
else note = run('git log -1 --format=%s');

const now = new Date();
const pad = (n) => String(n).padStart(2, "0");
const stamp = `${now.getFullYear()}${pad(now.getMonth() + 1)}${pad(now.getDate())}-${pad(now.getHours())}${pad(now.getMinutes())}`;
const version = `${stamp}-${shortHash()}`;
const builtAt = now.toISOString();

// 1) 静态文件：next build 会原样拷入 out/，部署后浏览器/curl 均可验证
writeFileSync(join(root, "public", "version.txt"), version + "\n", "utf8");

// 2) version.json：前端「检测新版本 + 更新说明」用（NavBar fetch 比对，仅客户端）
writeFileSync(
  join(root, "public", "version.json"),
  JSON.stringify({ version, builtAt, note }, null, 2) + "\n",
  "utf8"
);

// 3) TS 常量：页面显示用，构建时内联
writeFileSync(
  join(root, "lib", "version.ts"),
  `// AUTO-GENERATED by scripts/make-version.mjs — 构建前自动更新，请勿手改\nexport const APP_VERSION = ${JSON.stringify(version)};\n`,
  "utf8"
);

console.log(`[version] generated: ${version}${note ? ` (note: ${note})` : ""}`);
