// 生成版本号并写入 public/version.txt（供线上 curl 验证）+ lib/version.ts（供页面显示）。
// 版本格式：YYYYMMDD-HHmm-<git short hash>，每次构建前运行。
// 用法：node scripts/make-version.mjs（已挂到 package.json 的 build 前置）
import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

function shortHash() {
  try {
    return execSync("git rev-parse --short HEAD", { cwd: root, encoding: "utf8" }).trim();
  } catch {
    return "nogit";
  }
}

const now = new Date();
const pad = (n) => String(n).padStart(2, "0");
const stamp = `${now.getFullYear()}${pad(now.getMonth() + 1)}${pad(now.getDate())}-${pad(now.getHours())}${pad(now.getMinutes())}`;
const version = `${stamp}-${shortHash()}`;

// 1) 静态文件：next build 会原样拷入 out/，部署后浏览器/curl 均可验证
writeFileSync(join(root, "public", "version.txt"), version + "\n", "utf8");

// 2) TS 常量：页面底部显示用，构建时内联
writeFileSync(
  join(root, "lib", "version.ts"),
  `// AUTO-GENERATED by scripts/make-version.mjs — 构建前自动更新，请勿手改\nexport const APP_VERSION = ${JSON.stringify(version)};\n`,
  "utf8"
);

console.log(`[version] generated: ${version}`);
